# Borrowed from Ben
# https://github.com/bpmct/coder-project-template/blob/main/.github/workflows/build-image.yaml

name: build-image
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Get short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # Change projectname in both places:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/joe-image:latest, ${{ secrets.DOCKERHUB_USERNAME }}/joe-image:${{ steps.vars.outputs.sha_short }}
          context: .
          file: ./Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}